version: '3.8'

services:
  proxyserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    restart: unless-stopped